[package]
name = "violette"
version = "2.1.2"
edition = "2021"

[dependencies]
maud = "0.26.0"
copy_dir = "0.1.3"
log = "0.4.21"
simple_logger = "5.0.0"
ureq = { version = "2.9.7", features = ["json"] }
serde = { version = "1.0.202", features = ["derive"] }
chrono = "0.4.38"
